# Generated by Django 2.2.4 on 2021-01-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wifi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instlCtprvnNm', models.CharField(max_length=20)),
                ('instlSignguNm', models.CharField(max_length=20)),
                ('instlNm', models.CharField(max_length=200)),
                ('instlLcDesc', models.CharField(max_length=200)),
                ('svcProvdNm', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
            ],
        ),
    ]
